/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        type: {
          normal: '#ffc267',
          fighting: '#549cb0',
          flying: '#84ced6',
          poison: '#cb6eff',
          ground: '#ffa26e',
          rock: '#7f7f7f',
          bug: '#ab70e2',
          ghost: '#847fb9',
          steel: '#dfdfdf',
          fire: '#fc6c6d',
          water: '#75bcff',
          grass: '#49d0b0',
          electric: '#ffd76e',
          psychic: '#e270c8',
          ice: '#9ef3fd',
          dragon: '#e5a0a0',
          dark: '#525477',
          fairy: '#ffacef',
          unknown: '#fc6c6d',
          shadow: '#67427b',
        },
      },
    },
  },
  safelist: [
    'bg-type-normal',
    'bg-type-fighting',
    'bg-type-flying',
    'bg-type-poison',
    'bg-type-ground',
    'bg-type-rock',
    'bg-type-bug',
    'bg-type-ghost',
    'bg-type-steel',
    'bg-type-fire',
    'bg-type-water',
    'bg-type-grass',
    'bg-type-electric',
    'bg-type-psychic',
    'bg-type-ice',
    'bg-type-dragon',
    'bg-type-dark',
    'bg-type-fairy',
    'bg-type-unknown',
    'bg-type-shadow',
  ],
  plugins: [],
}
